# Generated by Django 5.2.1 on 2025-06-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('activity', 'Learning Activity'), ('achievement', 'Achievement'), ('milestone', 'Developmental Milestone'), ('note', 'Progress Note')], default='note', max_length=20),
        ),
    ]
