# Generated by Django 5.2.1 on 2025-06-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/media/'),
        ),
    ]
