# Generated by Django 5.2.1 on 2025-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0008_siteconfig_connect_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_name',
            field=models.CharField(default='LittleTales', help_text='Name of your site', max_length=50),
        ),
    ]
