# Generated by Django 5.2.1 on 2025-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0009_alter_siteconfig_logo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='connect_description',
            field=models.TextField(default="Monitor your child's development and achievements in real-time.", help_text='Description for the progress tracking feature'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='connect_heading',
            field=models.CharField(default='Track Progress', help_text='Heading for the progress tracking feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='learn_description',
            field=models.TextField(default='Track academic, social, and emotional development milestones.', help_text='Description for the development feature'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='learn_heading',
            field=models.CharField(default='Development', help_text='Heading for the development feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='register_text',
            field=models.CharField(default="New here? Join our community today to document your child's learning journey.", help_text='Text for the register section', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='share_description',
            field=models.TextField(default="Capture and share your child's learning moments with family and teachers.", help_text='Description for the sharing feature'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='share_heading',
            field=models.CharField(default='Share Moments', help_text='Heading for the sharing feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sign_in_text',
            field=models.CharField(default="Already have an account? Sign in to share and track your child's progress.", help_text='Text for the sign in section', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='welcome_subtitle',
            field=models.CharField(default="A place for sharing children's learning journeys", help_text='Welcome page subtitle text', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='welcome_title',
            field=models.CharField(default='Welcome to LittleTales', help_text='Main welcome page title', max_length=100),
        ),
    ]
