# Generated by Django 5.2.1 on 2025-06-02 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years')], max_length=10)),
                ('category', models.CharField(choices=[('language', 'Language Development'), ('math', 'Mathematics'), ('science', 'Science'), ('social', 'Social Studies'), ('physical', 'Physical Development'), ('creative', 'Creative Arts'), ('emotional', 'Emotional Development')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['age_group', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('language', 'Language Development'), ('math', 'Mathematics'), ('science', 'Science'), ('social', 'Social Studies'), ('physical', 'Physical Development'), ('creative', 'Creative Arts'), ('emotional', 'Emotional Development')], max_length=50)),
                ('age_group', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years')], max_length=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('materials_needed', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='early_learning/resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='early_learning.learningactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='children.child')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='early_learning.learningactivity')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('child', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('achievement_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to='children.child')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='early_learning.developmentmilestone')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('child', 'milestone')},
            },
        ),
    ]
