# Generated by Django 5.2.1 on 2025-06-02 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_learning', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('learning', 'Learning'), ('development', 'Development'), ('achievement', 'Achievement'), ('system', 'System')], default='learning', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('activity_completed', 'Activity Completed'), ('milestone_achieved', 'Milestone Achieved'), ('new_activity', 'New Activity Available'), ('progress_update', 'Progress Update'), ('reminder', 'Reminder'), ('alert', 'Alert')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('never', 'Never')], default='immediate', max_length=20)),
                ('activity_completed_enabled', models.BooleanField(default=True)),
                ('milestone_achieved_enabled', models.BooleanField(default=True)),
                ('new_activity_enabled', models.BooleanField(default=True)),
                ('progress_update_enabled', models.BooleanField(default=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('email_priority_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_type', models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('loud', 'Loud'), ('custom', 'Custom')], default='medium', max_length=20)),
                ('browser_notifications_enabled', models.BooleanField(default=True)),
                ('browser_notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='immediate', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
