# Generated by Django 5.2.1 on 2025-06-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
    ]
